import os
import sys
from pathlib import Path
from dotenv import load_dotenv
import dspy

from src.decompile_dspy.pipeline import DecompileRefinePipeline

load_dotenv()

def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/run_refine.py <index>")
        print("Example: python scripts/run_refine.py 0")
        sys.exit(1)

    idx = sys.argv[1]
    sample_path = Path(f"post-pro/output{idx}.c")

    if not sample_path.exists():
        print(f"File not found: {sample_path}")
        sys.exit(1)

    lm = dspy.LM(model=os.getenv("DSPY_MODEL", "gpt-4o-mini"))
    dspy.settings.configure(lm=lm)

    ghidra_code = sample_path.read_text(encoding="utf-8")

    print("====== Ghidra input ======")
    print(ghidra_code)

    pipe = DecompileRefinePipeline()
    out = pipe(ghidra_code=ghidra_code)

    print("\n====== Final C code ======")
    print(out.final_c)

    print("\n====== Debug info, generated by the LLM======")
    print(out.debug)

    out_dir = Path("refined")
    out_dir.mkdir(exist_ok=True)

    out_file = out_dir / f"refined{idx}.c"
    out_file.write_text(out.final_c)

    print(f"\nSaved to: {out_file}")


if __name__ == "__main__":
    main()





    